### ISSUE TITLE
Error running restore-indexes: ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS

### ISSUE THREAD

**Issue by thefoxwings** [awslabs/amazon-documentdb-tools#105]
Hello! I'm trying to import multiple indexes for a single db in an empty DocDB cluster before we connect to DMS. I ran the following command on a rhel 8.9 ec2 instance and got the following error:

`# sudo python3.8 migrationtools/documentdb_index_tool.py --restore-indexes --skip-incompatible --dir <dir> --uri 'mongodb://<user>:<password>@<endpoint>:<port>/?tls=true&tlsCAFile=<pem-file>&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false'`

output:
`024-03-25 17:58:14,970: Connecting to instance using provided URI
Traceback (most recent call last):
  File "migrationtools/documentdb_index_tool.py", line 638, in <module>
    main()
  File "migrationtools/documentdb_index_tool.py", line 634, in main
    indextool.run()
  File "migrationtools/documentdb_index_tool.py", line 527, in run
    connection = self._get_db_connection(self.args.uri)
  File "migrationtools/documentdb_index_tool.py", line 142, in _get_db_connection
    mongodb_client.admin.command('ismaster')
  File "/usr/local/lib64/python3.8/site-packages/pymongo/_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/pymongo/database.py", line 890, in command
    with self.__client._conn_for_reads(read_preference, session) as (
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib64/python3.8/site-packages/pymongo/mongo_client.py", line 1330, in _conn_from_server
    with self._checkout(server, session) as conn:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib64/python3.8/site-packages/pymongo/mongo_client.py", line 1252, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib64/python3.8/site-packages/pymongo/pool.py", line 1637, in checkout
    conn = self._get_conn(handler=handler)
  File "/usr/local/lib64/python3.8/site-packages/pymongo/pool.py", line 1756, in _get_conn
    conn = self.connect(handler=handler)
  File "/usr/local/lib64/python3.8/site-packages/pymongo/pool.py", line 1607, in connect
    conn.authenticate()
  File "/usr/local/lib64/python3.8/site-packages/pymongo/pool.py", line 1078, in authenticate
    auth.authenticate(creds, self, reauthenticate=reauthenticate)
  File "/usr/local/lib64/python3.8/site-packages/pymongo/auth.py", line 625, in authenticate
    auth_func(credentials, conn)
  File "/usr/local/lib64/python3.8/site-packages/pymongo/auth.py", line 530, in _authenticate_default
    return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
  File "/usr/local/lib64/python3.8/site-packages/pymongo/auth.py", line 242, in _authenticate_scram
    data = _password_digest(username, credentials.password).encode("utf-8")
  File "/usr/local/lib64/python3.8/site-packages/pymongo/auth.py", line 328, in _password_digest
    md5hash = hashlib.md5()  # noqa: S324
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS`

I have the following pip packages installed:

`pymongo==4.6.2
dnspython==2.6.1`

Fell down a rabbit hole regarding FIPS vs md5, which involved making changes to the pymongo pip, but didnt wanna go that far. Confirmed username and password is valid and can connect to docdb instance. Any guidance would be appreciated!

**Comment by tmcallaghan** [comment]
Can you please simplify a few things, specifically -

**Comment by thefoxwings** [comment]
> Can you please simplify a few things, specifically remove "&replicaSet=rs0&readPreference=secondaryPreferred" from your URI and verify that you are either using the cluster endpoint or endpoint for your primary instance?

Was calling the cluster endpoint, not the primary endpoint. Cluster only has one node at this time. Ended up creating associated blank .bson files and ran a mongorestore. ty for your help!
