### ISSUE TITLE
uri need to handle special characters

### ISSUE THREAD

**Issue by rrossouw01** [awslabs/amazon-documentdb-tools#122]
Hi apologies if already dealt with.  We have a password with special character and the index tool is not able to parse it.

`$ python3 migrationtools/documentdb_index_tool.py --restore-indexes --skip-incompatible --dir /tmp/mongo-to-docdb/tmp_mongodb_index_export --uri 'mongodb://our_user:our_password@our-documentdb.cluster:27017/?tls=true&tlsCAFile=../../rds-combined-ca-bundle.pem&replicaSet=rs0&retryWrites=false'
2024-06-25 09:37:16,948: Connecting to instance using provided URI
Traceback (most recent call last):
  File "/home/ubuntu/mongo-to-docdb/amazon-documentdb-tools/index-tool/migrationtools/documentdb_index_tool.py", line 644, in <module>
    main()
  File "/home/ubuntu/mongo-to-docdb/amazon-documentdb-tools/index-tool/migrationtools/documentdb_index_tool.py", line 640, in main
    indextool.run()
  File "/home/ubuntu/mongo-to-docdb/amazon-documentdb-tools/index-tool/migrationtools/documentdb_index_tool.py", line 533, in run
    connection = self._get_db_connection(self.args.uri)
  File "/home/ubuntu/mongo-to-docdb/amazon-documentdb-tools/index-tool/migrationtools/documentdb_index_tool.py", line 140, in _get_db_connection
    mongodb_client = MongoClient(host=uri,appname='indxtool')
  File "/usr/local/lib/python3.10/dist-packages/pymongo/mongo_client.py", line 736, in __init__
    res = uri_parser.parse_uri(
  File "/usr/local/lib/python3.10/dist-packages/pymongo/uri_parser.py", line 516, in parse_uri
    user, passwd = parse_userinfo(userinfo)
  File "/usr/local/lib/python3.10/dist-packages/pymongo/uri_parser.py", line 71, in parse_userinfo
    raise InvalidURI(
pymongo.errors.InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus`

**Comment by tmcallaghan** [comment]
Can you please further describe the special character? In the example your provided I see an underscore between "our" and "password".

**Comment by rrossouw01** [comment]
that are not real. I removed the real.  username has no special characters. password has a percentage sign.

**Comment by tmcallaghan** [comment]
As it shows in the error message, you need to make sure your username and password are escaped according to RFC 3986. In your example you have a password containing the % character. You can simply escape the % by using %25 instead.

**Comment by rrossouw01** [comment]
thank you that works.  should have read the RFC or the error closer.  I was doing backslash to escape like I usually do in bash.

**Comment by tmcallaghan** [comment]
No issue.
